# SonarQube Project Properties
sonar.projectKey= newproject    # Replace with your actual project key from SonarQube
sonar.projectName=newproject    # Replace with your actual project name
sonar.projectVersion=1.0                # Replace with your version number
sonar.sources=src                       # Adjust this to the directory where your source code is located
sonar.host.url=${{ secrets.SONAR_HOST_URL }}  # URL to SonarQube server (configured in GitHub Secrets)
sonar.login=${{ secrets.SONAR_TOKEN }}       # Authentication token from SonarQube (configured in GitHub Secrets)
