name: Deploy to Local Machine

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

  deploy:
    name: Deploy to Local Machine
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop my-app || true
          docker rm my-app || true

      - name: Run New Container
        run: |
          docker run -d -p 3000:3000 --name my-app ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
